name: Docker Build CI

on:
  push:
    branches:
    - 'master'
    - 'main'

jobs:
  ghcr-build:
    strategy:
      matrix:
        include:
          - hugo-version: 0.59.1
            extended: false
          - hugo-version: 0.69.0
            extended: false
          - hugo-version: 0.70.0
            extended: true
          - hugo-version: 0.74.0
            extended: true
          - hugo-version: 0.81.0
            extended: true
          - hugo-version: 0.110.0
            extended: true
          - hugo-version: 0.133.0
            extended: true
        
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push ${{ matrix.hugo-version }} image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            HUGO_VERSION=${{ matrix.hugo-version }}
            HUGO_EXTENDED=${{ matrix.extended }}
          tags: ghcr.io/uvarc/hugo-build:prod-${{ matrix.hugo-version }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
